### ISSUE TITLE
Theme partially activated on install

### ISSUE THREAD

**Issue by duien** [sashimacs/os1-theme#5]
When I install this theme through straight, it is immediately activated even without loading the theme. The value of `custom-enabled-themes` is not changed, and I am not prompted to confirm loading. 

I'm able to reproduce this with an extremely minimal configuration, starting emacs with `emacs -q` and running the following:

~~~
(setq straight-repository-branch "develop")
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(use-package os1-theme
  :straight (:type git :host github :repo "sashimacs/os1-theme"))
~~~

I'm on emacs 29 in case that makes a difference. Happy to provide additional info if it would be helpful.

**Comment by sashimacs** [comment]
Looking into this — I think it has something to do with `use-package` requiring the os1-theme file directly.

As a workaround, you can use `:defer t`, e.g.

```emacs-lisp
(use-package os1-theme
  :defer t
  :straight (:type git :host github :repo "sashimacs/os1-theme"))
```

This will make `os1` available as a theme by `load-theme`, but won't automatically load on startup. It also lets `disable-theme` correctly reset back to default if you do `load-theme`.

**Comment by duien** [comment]
Thanks for looking into it, and for the work-around. That does seem to fix the issue, but I've never had to do that for any other theme, so definitely something funny going on.

I'm enjoying the theme so far! Great to see another light theme out there. Thank you!

**Comment by duien** [comment]
I spend a bit of time digging into this, and I think it's actually an issue with the solarized themes, not with yours specifically. So, for instance, running `(require 'solarized-dark-theme)` loads that theme's customizations without enabling the theme, just like I saw with OS1. It's less obvious there because the main file doesn't correspond directly to one of the themes, so it only manifests when requiring a specific theme, but it seems to be the exact same problem and there's a number of open issues in that repo relating to it.

**Comment by sashimacs** [comment]
Working on a change that will fix this where the theme will be defined with [autothemer](https://github.com/jasonm23/autothemer) instead of using solarized.

**Comment by sashimacs** [comment]
Just merged this, please try it out!

**Comment by duien** [comment]
Works beautifully! Thank you!

Autothemer is pretty great. It's what I use for the themes I've put together as well.
